name: ecommercefood
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Group 3.png
    - assets/images/Group 33.png
    - assets/images/Group 35.png
    - assets/images/Group 6925.png
    - assets/images/Group 6925 (1).png
    - assets/images/Verification.png
    - assets/images/Rectangle 18 (1).png
    - assets/images/illustration.png
    - assets/images/text.png
    - assets/images/Your zone.png
    - assets/images/Your area.png
    - assets/images/Group.png
    - assets/images/text (1).png
    - assets/images/text (2).png
    - assets/images/Naviagtion.png
    - assets/images/Mask Group.png
    - assets/images/2771 1.png
    - assets/images/banana.png
    - assets/images/pngfuel 1.png
    - assets/images/92f1ea7dcce3b5d06cd1b1418f9b9413 3.png
    - assets/images/pngfuel 3.png
    - assets/images/Pulses.png
    - assets/images/Rice.png
    - assets/images/pngfuel 4.png
    - assets/images/pngfuel 5.png
    - assets/images/bottom bar.png   
    - assets/images/Vector.png
    - assets/images/Group 292.png
    - assets/images/beef bone.png
    - assets/images/pngfuel 9.png
    - assets/images/pngfuel 6.png
    - assets/images/pngfuel.png
    - assets/images/pngfuel 6 (1).png
    - assets/images/Group 6824 (1).png
    - assets/images/Group 6841.png
    - assets/images/Group 6845.png
    - assets/images/pngfuel 12.png
    - assets/images/Group 6843.png
    - assets/images/pngfuel 13.png
    - assets/images/pngfuel 14.png
    - assets/images/pngfuel 16.png
    - assets/images/pngfuel 18.png
    - assets/images/hiclipart 2.png
    - assets/images/egg-noodle (1) 2.png
    - assets/images/American-Garden-Mayonnaise-Eggless-473ml 2 (1).png
    - assets/images/rp_24790392_0053554627_l 2.png
    - assets/images/Group 6863.png
    - assets/images/Group 6864.png
    - assets/images/Group 6865.png
    - assets/images/Group 6866.png
    - assets/images/Group 6872.png
    - assets/images/image 13.png
    - assets/images/Rectangle 82.png
    - assets/images/Group 45.png

    
    



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
